MathLebl/contre_pied_prod

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_annimation_swup.scss
- app/views/layouts/application.html.erb
Partial "_animation-swup.scss" créée
Première transition : *fade*
> Swup initiation

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/pages/_artist-show.scss
- app/assets/stylesheets/pages/_index.scss
- app/views/artists/show.html.erb
création du fichier 
*_artist-show.scss*
Modification de la structure page
Modification du Banner
> Page Artist#show redesign

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/components/_table.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
Couleur de Background
Couleur de font
Couleur de border
> couleurs mises à jour

- app/views/artists/show.html.erb
- db/migrate/20200506074318_add_more_columns_to_artists.rb
- db/schema.rb
- db/seeds/artists-seed.rb
- db/seeds/event-seed.rb
> ajustement du model artists pour les photos

- app/views/shared/_event-table.html.erb
> Add link to the artist page from agenda

- app/admin/orders.rb
Rien de ouf, juste l'ajout d'un tableau Orders dans activ admin
> Orders added to dashboard

- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
Normalement j'ai réglé le problème de Toggle, en enlevant swup. 
Il reste la gem mais elle n'est plus initialisé
> Toggle fixed, swup désactivé

- app/javascript/packs/application.js
- app/javascript/stylesheets/application.scss
- app/views/layouts/application.html.erb
- package.json
- postcss.config.js
- tailwind.config.js
- yarn.lock
- Install tailwind css
**WARNING :** Bootstrap is still enable, it's possible that there is some conflicts between their classes. The goal is to fully disable bootstrap as soon as possible. We just waiting to repare navbar without Bootstrap classes and here we go !
> add tailwind

- app/assets/stylesheets/pages/_index.scss
- app/javascript/packs/application.js
> vestige de swup (qui casse bien les couilles pour rien) supprimés

- app/admin/artists.rb
- app/views/artists/show.html.erb
Ajout formulaire dans "à la mano" dans Artist admin, pour autoriser les arrays
> List Info FONCTIONNE

- Procfile
- app/admin/actus.rb
- app/admin/artists.rb
- app/admin/dashboard.rb
- app/admin/orders.rb
- app/admin/products.rb
- app/models/actu.rb
- app/models/artist.rb
- app/models/order.rb
Modifications des tableaux Active Admin.
Ajout de scopes
Ajout de liens direct vers le site (artist, products)
> Active admin updates

- Procfile
procfile modifié pour corriger une erreur
> rake seed delete

- app/controllers/orders_controller.rb
- app/controllers/products_controller.rb
- app/views/products/show_cart.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
- Sont rattachées à la view show cart, qui est un index de tous les produits ajoutés au panier par l'utilisateur.
- On peut désormais **ajouter**, **supprimer**, et simplement **voir le contenu** des objets dans le panier.
- Sert à calculer le **prix total** des produits dans le panier _(créée pour résoudre le souci d'affichage du prix)_
ℹ️ Pour le moment **sans style** ℹ️ , display les infos : 
- Nom
- prix unitaire
- photo
- prix total
- passer commande
_à noter que le bouton passer commande ne fonctionne pas encore, c'est prévu pour la page récapitulative commande, je sais pas encore comment faire mais je trouverai bien une solution_ 👍
- nouvelles routes pour le panier
- ajout du bouton panier dans la navbar lorsqu'un user est connecté 👍
> Show cart page

- Gemfile
- Gemfile.lock
- app/uploaders/illustration_uploader.rb
- app/uploaders/image_uploader.rb
- app/uploaders/press_file_uploader.rb
- config/initializers/carrierwave.rb
AWS and S3 comme DB pour les upload CarrierWave
> aws set for CarrierWave in production

- app/controllers/orders_controller.rb
- app/controllers/products_controller.rb
- app/models/order.rb
- app/services/cart.rb
- app/views/orders/new.html.erb
- app/views/orders/show.html.erb
- app/views/payments/new.html.erb
- app/views/products/show.html.erb
- config/routes.rb
- db/migrate/20200625101211_add_userinfos_to_orders.rb
- db/migrate/20200625125025_remove_productinfos_from_orders.rb
- db/schema.rb
- Ajout des colonnes **Address, city, zip_code, et phone**
- Modif du code existant pour coller aux nouvelles colonnes 
- Ajout d'un formulaire, et modification des pages de récapitulatif de commande
- J'ai déplacé le code relatif au pannier des articles dans un service histoire de pouvoir synthétiser un peu le code, étant donné qu'on doit l'appeler à 2 endroits différents
-Ajout d'une méthode pour remettre le pannier à 0 quand l'utilisateur à payé sa commande
- Suppression des colonnes **product_name, product_id** dans la table orders
- Suppression du code devenu inutile
Création de la route order/new pour accueillir le formulaire d'adresse de livraison
⚠️ Comme d'habitude, j'ai accordé peu d'importance au style étant donné que quand on va l'attaquer, beaucoup de choses seront …
> Order address

- config/storage.yml
modification des paramètre de Storage.yml pour S3
> storage.yml modified for S3

- config/database.yml
- config/environments/staging.rb
- config/webpacker.yml
Création du fichier Environement/staging.rb
Modification des fichiers webpacker.yml et database.yml pour le staging
> environement/staging.rb create, webpacker.yml and database.yml modified

- app/assets/stylesheets/components/_table.scss
- app/views/pages/home.html.erb
- app/views/shared/_event-table.html.erb
réparation du malheureux push sur master
> Revert master push

- app/assets/config/manifest.js
- app/assets/stylesheets/pages/_home.scss
- app/views/pages/home.html.erb
- tailwind.config.js
- Voir photo ci-joint : C'est probablement pas parfait pour le moment, sachant qu'avec Sam on s'était mis d'accord sur un type d'animation bien précise lorsque l'on survole une miniature, **mais je n'y suis pas arrivé...** à voir si c'est faisable sans prise de tête. 
- Pour le moment je me suis contenté de faire un css assez simple mais qui ne fait pas tâche, vous me ferez un retour dessus !
- ⚠️ J'ai uncomment le link application.css dans manifest.js car rien ne fonctionnait sans, à voir si c'est normal ou non ⚠️
> Header home

- app/assets/stylesheets/components/_table.scss
- app/views/pages/home.html.erb
- app/views/shared/_event-table.html.erb
- Modif de la couleur du fond
- Modif de la couleur du texte
- Ajout de quelques animations de scale pour rendre la compréhension plus simple de ce qui est cliquable ou non
- Mise en position absolue du titre **Agenda**
- Ajustements margin / padding etc.
_Voilà à quoi ça ressemble_
> Agenda style

- app/views/shared/_actus.html.erb
correction d'une erreur dans views/actus
> bug fixed in actus view

- config/database.yml
changed staging credential in database.yml
> database.yml modification

- config/storage.yml
Nouvelle tentative
Modification dans storage.yml
AWS_BUCKET en S3_BUCKET
> storage.yml modifications

- app/assets/config/manifest.js
tentative de correction pour la prod
> try something in manifest

- app/assets/stylesheets/components/_table.scss
- app/assets/stylesheets/show.scss
- app/views/artists/concert.html.erb
- app/views/artists/jeune_public.html.erb
- app/views/artists/show.html.erb
- app/views/artists/spectacle.html.erb
- app/views/events/index.html.erb
- app/views/shared/_event-table-artist.html.erb
- app/views/shared/_event-table.html.erb
- Les pages **Spectacles**, **Concerts**, **Jeune public**, et **Agenda** ont maintenant un agenda qui à la même logique de design.
- Ca rends encore mal sur certaines pages à cause du design des anciens composants qui n'ont pas encore été remplacés, mais tout devrait être ok après !
> Harmonize agendas

- app/assets/stylesheets/components/_table.scss
- app/assets/stylesheets/show.scss
- app/views/artists/show.html.erb
- app/views/shared/_event-table-artist.html.erb
- app/views/shared/_event-table.html.erb
- Harmonisation du design pour qu'il colle avec la page **"Home"**
Pas grand chose à ajouter, maintenant que les 2 modèles sont faits, je vais faire une autre branche pour que tous les agenda restants aient un titre et un margin identique ce qui n'est pas encore le cas
> Agenda artist style

- config/webpacker.yml
Modification de webpacker.yml
copie des settings de staging pour production
On ne sait jamais
> dernière tentative sur webpack avant de faire un break

- config/storage.yml
> region change

- app/admin/products.rb
- app/models/product.rb
Ajout de product_image dans product pour gérer avec S3
**Je n'ai pas encore fait la partie view, pour des raisons évidentes de db vide et parce que j'avais pas envie de me prendre la tête la dessus pour le moment**
> product_image create

- app/admin/artists.rb
- app/models/artist.rb
- app/views/artists/show.html.erb
Creation de banner_image et de 4 show_image pour Artist
View faite mais ça demandera à être cleaner après migration vers S3 des images de tous les artists
> banner_image et show_image x4 create

- app/views/shared/_actus.html.erb
correction d'un bug pour la production
> actu fixed for production

- app/admin/orders.rb
Encore des trucs commenté dans admin Order le temps de réglé les bayes avec items
> comment some in order again

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/show.scss
- app/views/artists/show.html.erb
- Recadrage de la photo en banner
- Mise en place du fond de couleur
- Mise en place de la partie "Qui est-ce ?" avec l'encadré rose foncé
- Mise en place de CSS grid pour le display de toutes les miniatures
- Modification des liens (facebook youtube etc.) pour les positionner sous la banner
⚠️ Je ne suis malheureusement pas assez calé en front pour faire un machin aux petits oignons... J'espère que Sam pourra arriver à fixer toutes les petites imperfections ! Le gros est fait on va dire.
Par contre à mon sens (à vérifier auprès de sam) il faudrait faire en sorte que toutes les photos des artistes soient de la même dimension, idem pour les miniatures, sinon ça va forcément poser un souci d'alignement un jour ou l'autre... ⚠️ 
ℹ️ Les header et footer ne sont pas encore fait, ça sera …
> Design artist page

- db/seeds/ajanjuez_seed.rb
- db/seeds/artists-seed.rb
- db/seeds/buissons_seed.rb
- db/seeds/goguette-seed.rb
- db/seeds/market_seed.rb
- db/seeds/news-seed.rb
- db/seeds/presque_seed.rb
- db/seeds/z_event_seed.rb
Toutes les seeds commentées sauf la partie USer pour pouvoir facilement créer les admin le temps de refaire les db staging et prod en réel
> seed commentées sauf User

- app/admin/artists.rb
- app/models/artist.rb
- app/models/credit.rb
- app/models/distribution.rb
- app/models/partenaire.rb
- app/models/presse.rb
- db/migrate/20200710155129_create_distributions.rb
- db/migrate/20200710162537_create_credits.rb
- db/migrate/20200710163033_create_presses.rb
- db/migrate/20200710163320_create_partenaires.rb
- db/migrate/20200710172357_remove_others_columns_to_artists.rb
- db/schema.rb
- test/models/credit_test.rb
- test/models/distribution_test.rb
- test/models/partenaire_test.rb
- test/models/presse_test.rb
Creation des models 
Partenaires
Presse
Distribution
Crédits 
afin de pouvoir gérer plus simplement le coté "array" de ces éléments dans l'interface active admin
Plus autre migration pour supprimer les columns inutiles (deezer, banner, dice 1,2,3 et 4, presse, distrib, credits et partenaires)
> Distrib as table

- app/views/artists/show.html.erb
artist/show modifié pour la banner en bg
> banner path bug with S3 again

- app/controllers/artists_controller.rb
- app/views/artists/show.html.erb
Modification de artist/show suite aux modification de la table
suppression de 
-deezer
-images Dice
remplacement de @artist.distribution par @distributions 
même chose pour partnaire, presse et credit
> Show clean

- app/controllers/artists_controller.rb
Ajout des vaiables d'instance pour le artist/show_jp
> controller artist modif for new instance

- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_navbar.scss
- app/views/shared/_footer.html.erb
- app/views/shared/_navbar.html.erb
- Autant que possible passage du design de CSS à **tailwind**
- nouvel agencement pour correspondre au Figma
- Ajout d'animations au hover dans la navbar et le footer
- Pour le moment toujours pas de logo --> **À faire** ℹ️ 
- Je me suis permis de commenter quelques liens dans la navbar :
Tous les liens vers _spectacles, jeune public etc._ car il avaient tendance à surcharger le haut de la page... À voir
J'ai également enlevé le bouton **Admin** du footer, et j'ai rajouter un bouton "**se connecter** dans la navbar.
Le passage dans la partie _Admin_ se fait comme avant dans la navbar et uniquement ici. ℹ️ Le bouton _Gestion_ à été mis dans un **if** pour qu'il ne soit visible uniquement si l'utilisateur connecté est admin.
> Header and footer

- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
Button style pour Dossier de presse
> add button style to Dossier de Presse

- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
Ajout d'un if empty? sur les socials links afin de n'avoir que les actifs
> if empty add to socials

- app/admin/artists.rb
- app/admin/dashboard.rb
Modification du show et du form pour admin/artist
Ajout des nested ressources (presse, credit, partenaires, distrib)
> Artist admin modif

- app/admin/actus.rb
- app/admin/artists.rb
- app/admin/dashboard.rb
- app/models/actu.rb
- db/migrate/20200711141824_remove_artist_to_actus.rb
- db/schema.rb
Suppression du liens Actu/Artist
**db:migrate a prévoir** 
Menus modifications sur admin/actus et dashboard
> admin modif et artist ref delete from actu

- app/admin/events.rb
- app/views/shared/_event-table.html.erb
Ajout de la ville dans l'agenda
modification de la partie admin
> Event Table upgrade

- app/admin/events.rb
- app/views/events/index.html.erb
- app/views/events/show.html.erb
- app/views/shared/_event-table-artist.html.erb
- app/views/shared/_event-table.html.erb
réparation du **if ticket**
ajout style **City** - location
> agenda modified

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
Ajout de la fonction search pour event par date et par artist
> search event by artist and date

- app/admin/actus.rb
- app/admin/artists.rb
- app/models/artist.rb
- app/views/artists/show.html.erb
Ajout de video_artist pour vidéo en "dur"
modification de admin/artist
modification de model/artist
modification de artist/show
> ajout de video_artist pour video file

- app/views/artists/show_jp.html.erb
modification de artist/show_jp pourt la gestion de video en "dur"
> ajout video pour show jp

- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
correction de l'erreur dans artist/show et artist/show_jp
(@artist.artist.video en @artist.artist_video)
> bug video fixed, enfin on tente

- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
video_tag ne fonctionnant pas normalement avec active storage ajout de **rals_blob_path**
> là normalement ça marche

- app/controllers/pages_controller.rb
- app/views/pages/boutique.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
Ajout d'une route *pages#boutique*
Modification du path *E-Boutique* dans la Navbar
Ajout d'une method Boutique dans pageController
> création d'une page d'attente pour la boutique

- app/admin/artists.rb
- app/views/artists/show.html.erb
Ajout de method: :get sur button_to pour press_file
> method get on button press_file

- app/admin/artists.rb
Ajout fonction *Supprimer* pour le Dossier de Presse dans active admin
- Creation de member action Delete
-ajout span "supprimer" dans form artist
> delete function for press_file

- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
Ajout de link_to sign up in sign in page
"francisation" de certains termes
> minors changes in devise

- app/views/devise/sessions/new.html.erb
Devise new session redesign with form_for and Tailwind
> Form with tailwind

- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- Couleur et mise en forme du titre
- Rajout de quelques margins pour les liens du bas
- Changement de couleur des liens
- Espacement des inputs
> Modif signup design

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
Search fonctionne par Artist et par date pour l'agenda
Pour le moment je ne suis pas satisfait du format des dates mais je n'ai pas encore trouvé comment faire sans que tout saute
> Search by Artist or date fixed

- app/assets/stylesheets/components/_list.scss
- app/views/artists/concert.html.erb
- app/views/artists/index.html.erb
- app/views/artists/jeune_public.html.erb
- app/views/artists/show.html.erb
- app/views/artists/spectacle.html.erb
- app/views/shared/_list.html.erb
- Nouveau design
- CSS grid
- harmonisation des titres
- retouches mineures du CSS
> Index artist global

- app/assets/stylesheets/components/_list.scss
- app/views/shared/_list.html.erb
- filtre noir et blanc lorsque inactive = true
- hover scale désactivé 
- Texte inactif apparait au hover
- Filtre flou sur l'image
ℹ️ **Je n'ai pas rendu le clic impossible, je ne savais pas si c'était nécessaire ou non** 🤔
> Inactive show

- app/views/pages/boutique.html.erb
- "Encore un peu de patience... La boutique contrepied production arrive bientôt !"
etc.
> added a coming soon message on the eshop page

- app/assets/stylesheets/application.scss
- app/views/shared/_navbar.html.erb
Ajout d'un dropdown menu dans la navbar 
- Meilleure UX (plus besoin de repasser par la home page pour accéder aux index spec
- Connecter/Déconnecter pour alléger la NavBar
- Suppression de panier pour le moment
**Style pas définitif**
> dropdown and clean up

- app/views/shared/_footer.html.erb
Modification du Footer
- Ajout de Contacts
- Correction de Agenda avec events_path
> Add contacts to footer and event_path to Agenda

- app/assets/stylesheets/components/_table.scss
- app/views/artists/jeune_public.html.erb
- app/views/shared/_event-table.html.erb
- modif du padding
- alignement des items
- épaisseur et couleur des borders
- épaisseur du texte titre
> modified table according to the figma

- app/assets/stylesheets/components/_table.scss
- app/views/artists/concert.html.erb
- app/views/artists/jeune_public.html.erb
- app/views/artists/spectacle.html.erb
- app/views/events/index.html.erb
- app/views/pages/home.html.erb
> fixed the display for all the tables

- app/assets/stylesheets/components/_list.scss
- app/views/artists/index.html.erb
- app/views/shared/_list.html.erb
- background primary
- border sur les images pour trancher un peu
- des broutilles en plus
> added background primary and a border on thumbnails

- app/views/artists/concert.html.erb
- app/views/artists/spectacle.html.erb
- background sur spectacles
- background sur concerts
**Pour l'instant tout fonctionne nickel**
> Background on all pages

- app/assets/stylesheets/show-jp.scss
- app/assets/stylesheets/show.scss
- app/javascript/packs/application.js
- app/javascript/plugins/infoToggle.js
- app/views/artists/show.html.erb
Création d'un fichier *infoToggle.js* dans javascript/pluggins
Reste le Style à peaufiner et surement une modification pour faire à terme pour avoir add.classlist sur btn et remove.classlist partout ailleurs
> Toggle mecanic OK for info-list

- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/pages/about.html.erb
- app/views/pages/contacts.html.erb
- app/views/pages/home.html.erb
- app/views/pages/legals.html.erb
- app/views/shared/_actus.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_list.html.erb
> Minors corrections3

- app/admin/events.rb
- app/admin/products.rb
- app/views/artists/concert.html.erb
- app/views/artists/index.html.erb
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/artists/spectacle.html.erb
- app/views/shared/_actus.html.erb
- app/views/shared/_navbar.html.erb
> Minors modifs4

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/show.scss
- app/javascript/packs/application.js
- app/views/artists/show.html.erb
- config/initializers/assets.rb
- package.json
- yarn.lock
Changement de disposition des photos et vidéos dans show artist (volonté du client)
Ajout de Lightbox2 pour générer une gallery avec les img
> Show img vid

- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
Commente le bouton **Retour** sur les show artists pour lemoment parce que c'est moche et que j'ai pas trouvé comment le rendre beau
> Retour btn comment for the moment

- app/views/events/index.html.erb
Ajout d'un grid pour la bar de recherche Agenda
> Grid pour Search Bar

- app/assets/stylesheets/components/_actus.scss
Disable overflox vertical pour Actus
> Disable Y overflow

- app/admin/artists.rb
- app/assets/stylesheets/show-jp.scss
- app/assets/stylesheets/show.scss
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/pages/home.html.erb
Quelques changements à la sauvage pour être en place ce soir
> Minors changes

- app/admin/artists.rb
- app/controllers/artists_controller.rb
- db/migrate/20200720123425_add_ranking_to_artists.rb
- db/schema.rb
- Colonne **ranking** qui va contenir un **integer** pour classer les artistes
- Rajout de l'information du ranking sur **_Index et show_**
- Rajout de la modification du ranking sur **_Edit_**
ℹ️ Du coup, pour chaque artiste existant, il faudra **rajouter** une valeur de classement, différente pour chacun
⚠️ Si jamais on souhaite **modifier** le classement, il faudra alors **_absolument_** intervertir la valeur des 2 artistes que l'on souhaite changer de place
_Screenshots des nouveaux champs_ :
> Artists ranking

- app/assets/stylesheets/show.scss
- app/javascript/plugins/DropdownToggle.js
- app/javascript/plugins/infoToggle.js
- app/views/artists/show.html.erb
- JS du dropdown navbar
- JS de la catagorie distribution, presse etc.
- mise en position relative de la div de la div **info_text** qui contient le texte pour ne pas que tout soit décalé à l'apparition
- petit margin pour équilibrer le tout
> Toggle modif

- app/controllers/pages_controller.rb
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/pages/retraite.html.erb
- app/views/shared/_list.html.erb
- config/routes.rb
Gif retraite
Retouches diverses et variées
> Modifs encore

- app/admin/events.rb
- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- db/migrate/20200720163553_add_columns_to_events.rb
- db/migrate/20200720164649_remove_mounth_to_events.rb
- db/migrate/20200720164847_add_month_to_events.rb
- db/schema.rb
Creation de deux column pour la table event
- region
- month
et tout ce qui va avec
> searchbar modiefied

- db/migrate/20200720163553_add_columns_to_events.rb
Reverts MathLebl/contre_pied_prod#158
> Revert "corrections"

- app/admin/events.rb
- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- db/migrate/20200720163553_add_columns_to_events.rb
- db/migrate/20200720164649_remove_mounth_to_events.rb
- db/migrate/20200720164847_add_month_to_events.rb
- db/schema.rb
Reverts MathLebl/contre_pied_prod#157
> Revert "searchbar modiefied"

- app/controllers/events_controller.rb
- app/views/events/index.html.erb
- db/migrate/20200720214216_add_columns_to_events.rb
- db/schema.rb
Search Bar Agenda refaite
création de event.region et event.month
en esperant que celle-ci ne fasse pas tout péter
> search bar

- app/assets/stylesheets/components/_actus.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/pages/boutique.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_actus.html.erb
- app/views/shared/_list.html.erb
Correction de Typos
Spacing de la partie list-info/text-info
Transition duration changée pour Home
Margin left/right sur actu container
Positionnement de certaines photos
> Correction

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/shared/_actus.html.erb
Ajout de la Gem *Redcarpet*
Création du helper markdown
maj des pages artist/show, artist/show_jp et _actus
> render Markdown

- app/controllers/application_controller.rb
> correction d'un bug

- app/assets/stylesheets/components/_actus.scss
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/components/_table.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/events/index.html.erb
- app/views/pages/about.html.erb
- app/views/pages/contacts.html.erb
- app/views/pages/home.html.erb
- app/views/pages/legals.html.erb
- app/views/shared/_actus.html.erb
- app/views/shared/_event-table.html.erb
- app/views/shared/_footer.html.erb
- app/views/shared/_list.html.erb
- app/views/shared/_navbar.html.erb
> mobile responsive

- config/environments/production.rb
ajoute  *config.force_ssl = true* à environement/production.rb
> add force ssl to prod environement

- app/assets/stylesheets/pages/_home.scss
- app/controllers/orders_controller.rb
- app/views/orders/new.html.erb
- app/views/orders/show.html.erb
- app/views/payments/new.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- app/views/products/show_cart.html.erb
- app/views/shared/_navbar.html.erb
- db/seeds/market_seed.rb
#189 
- Réalisation du style de toutes les pages liées à la boutique (y'en aura certaines à revoir, car trop vides / mal agencées)
- Tous les boutons qui ne fonctionnaient pas sont maintenant opérationnels
- Il me reste à me pencher sur les badges
> Shop setup

- config/locales/devise.en.yml
Première partie de la "francisation" de devise
Je test aussi le model prjet/issues/PR de github avec cet élément
> première partie

- app/controllers/pages_controller.rb
- app/controllers/payments_controller.rb
- app/views/payments/new.html.erb
- config/routes.rb
#188 
- Mise en place d'un webhook qui actualise les payements selon 3 états
- Message d'alerte pour le remplissage du mail en attendant de trouver une solution plus viable
> first coding try of webhook implementation

- app/admin/orders.rb
- app/admin/products.rb
- app/models/order.rb
- app/models/shop_category.rb
Gestion du model Order dans la partie Back Office
> Back Office/Orders and Back Office/Products

- app/controllers/application_controller.rb
- app/controllers/users_controller.rb
- app/models/user.rb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/shared/_flashes.html.erb
Override user params for devise
Form registration and edit modiefied
Translate devise details in french
> Devise details

- app/assets/stylesheets/components/_table.scss
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
> fixed position of the table title

- app/controllers/orders_controller.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
> Little fixes

- app/views/shared/_navbar.html.erb
#203 
On peut merge immédiatement
> added connexion button if user isn't logged

- app/assets/stylesheets/pages/_show.scss
- app/views/artists/show.html.erb
Voir les captures d'écran : **Gauche :** Normal, **Droite :** Hover
J'ai juste un petit souci au niveau de l'animation, J'aimerais faire translater le retour de gauche à droite comme s'il sortait de la flèche, mais j'arrive pas à lui appliquer les bonnes propriétés 🤔
> test bouton retour sur artist show

- app/views/pages/about.html.erb
- app/views/pages/contacts.html.erb
- app/views/pages/legals.html.erb
Design pages text en chinoisant le design général
> Text pages style

- app/views/products/show.html.erb
#220 
- Design en accord avec le figma
- responsive
ℹ️ J'ai un peu de mal à adapter en version mobile, les images principalement... À voir ℹ️
> E-shop design (show)

- app/views/shared/_navbar.html.erb
- plus d'overflow en affichage mobile
> navbar organisation

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_list.scss
- app/assets/stylesheets/components/_table.scss
- app/views/artists/concert.html.erb
- app/views/artists/index.html.erb
- app/views/artists/jeune_public.html.erb
- app/views/artists/show.html.erb
- app/views/artists/show_jp.html.erb
- app/views/artists/spectacle.html.erb
- app/views/events/index.html.erb
- app/views/orders/new.html.erb
- app/views/products/show_cart.html.erb
- app/views/shared/_list.html.erb
#194 
- Responsive sur **artists/spectacles**
- **artists/concerts**
- **jeune public**
- **show_jp**
- **artists show**
- **artists index**
- **agenda**
- **show-cart**
- **orders new**
Il me semble pas avoir oublié de page en particulier 🤔 
Il reste cependant un souci sur lequel je ne me suis pas encore penché : la navbar prend un peu trop de place en mode téléphone.
Je ferai ça dans une PR exprès
> Responsive
